twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    paths:
        '%kernel.project_dir%/vendor/toiba/fullcalendar-bundle/Resources/views/Calendar': FullCalendarCalendar
    
