vich_uploader:
    db_driver: orm
    mappings:
         image_eleve:
             uri_prefix: /images/eleves
             upload_destination: '%kernel.project_dir%/public/images/eleves'

    #mappings:
    #    image_eleve:
    #        uri_prefix: /images/eleves
    #        upload_destination: '%kernel.project_dir%/public/images/eleves'
